version: "3.4"

x-common-variables: &common-variables
   TZ: "CHANGEIT"

services:
  citigo-revproxy:
    container_name: "citigo-revproxy"
    build: "./citigo-charge-monitor-revproxy"
    environment:
      <<: *common-variables
    ports:
      - "8080:8080"      
    depends_on:
      - citigo-api
      - citigo-app      
    restart: unless-stopped      

  citigo-db:
    container_name: "citigo-db"
    image: "mysql:8-oracle"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: "citigo"    
      MYSQL_USER: "citigo"
      MYSQL_PASSWORD: "citigo"
      MYSQL_DATABASE: "citigo_charge_monitor"
    restart: unless-stopped
    volumes:
      - "citigo-db-data:/var/lib/mysql"      

  citigo-redis:
    container_name: "citigo-redis"
    image: "bitnami/redis:6.2"
    environment:
      <<: *common-variables
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped      

  citigo-api:
    container_name: "citigo-api-server"
    build: "./citigo-charge-monitor-api-server"
    environment:
      <<: *common-variables
      CITIGO_DATABASE_URL: "mysql://citigo:citigo@citigo-db/citigo_charge_monitor"
      CITIGO_REDIS_URL: "redis://citigo-redis"
      CITIGO_API_BASE_ADDR: "0.0.0.0:8000"  
    depends_on:
      - citigo-db
      - citigo-redis
    restart: unless-stopped    

  citigo-worker:
    container_name: "citigo-worker"
    build: "./citigo-charge-monitor-worker"
    environment:
      <<: *common-variables
      CITIGO_API_BASE_URL: "http://citigo-revproxy:8080/api/"
      CITIGO_API_USERNAME: "CHANGEIT"
      CITIGO_API_PASSWORD: "CHANGEIT"
      CITIGO_SKODACONNECT_USERNAME: "CHANGEIT"  
      CITIGO_SKODACONNECT_PASSWORD: "CHANGEIT" 
      CITIGO_VEHICLE_VIN: "CHANGEIT"
    depends_on:
      - citigo-api
    restart: unless-stopped

  citigo-app:
    container_name: "citigo-app"
    build: "./citigo-charge-monitor-front-app" 
    environment:
      <<: *common-variables
    depends_on:
      - citigo-api
    restart: unless-stopped

volumes:
  citigo-db-data:
